about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('food/', views.AboutFoodView.as_view(), name='food'),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'recipes.views.page_not_found'
handler500 = 'recipes.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('recipes.urls')),
]

templates/small_templates/footer.html
<footer class="footer">
        <div class="footer__container container">
            <a href="{% url 'about:food' %}" class="footer__brand link">Продуктовый помощник</a>
            <ul class="footer__items">
                <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
                <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
            </ul>
        </div>
    </footer>

templates/small_templates/nav.html
<header class="header">
      <nav class="nav">
          <div class="nav__container container">
              <ul class="nav__items list">
                  <li class="nav__item {% if request.resolver_match.url_name == 'index' or request.resolver_match.url_name == 'profile' or request.resolver_match.url_name == 'single_recipe' %} nav__item_active{% endif %}">
                      <a href="{% url 'index' %}" class="nav__link link">Рецепты</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav__item {% if request.resolver_match.url_name == 'my_follow' %} nav__item_active {% endif %}">
                      <a href="{% url 'my_follow' %}" class="nav__link link">Мои подписки</a>
                  </li>
                  <li class="nav__item {% if request.resolver_match.url_name == 'new' %} nav__item_active {% endif %}">
                      <a href="{% url 'new' %}" class="nav__link link">Создать рецепт</a>
                  </li>
                  <li class="nav__item {% if request.resolver_match.url_name == 'favorites' %} nav__item_active {% endif %}">
                      <a href="{% url 'favorites' %}" class="nav__link link">Избранное</a>
                  </li>
                  <li class="nav__item {% if request.resolver_match.url_name == 'purchases' %} nav__item_active {% endif %}">
                      <a href="{% url 'purchases' %}" class="nav__link link">Список покупок</a>
                        <span class="badge badge_style_blue nav__badge" id="counter">{% if user.purchase.count > 0  %} {{ user.purchase.count }}{% endif %}</span>
                  </li>
                  {% endif %}
              </ul>
              <ul class="nav__items list">
                  {% if user.is_authenticated %}
                  <li class="nav__item"><a href="{% url 'profile' user.username %}" class="nav__link link">Моя страница</a></li>
                  <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                  <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                  {% else %}
                  <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                  <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
                  {% endif %}
              </ul>
          </div>
      </nav>
  </header>