about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('food/', views.AboutFoodView.as_view(), name='food'),
]

foodgram/urls.py
from django.contrib import admin
from django.urls import path, include

handler404 = 'recipes.views.page_not_found'
handler500 = 'recipes.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('recipes.urls')),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator, ValidationError
from django.db.models import Exists, OuterRef

User = get_user_model()


class Tag(models.Model):
    title = models.CharField('Название тега', max_length=50)
    display_name = models.CharField('Название тега для шаблона', max_length=50)
    color = models.CharField('Цвет тега', max_length=50)

    class Meta:
        verbose_name = 'тег'
        verbose_name_plural = 'теги'

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    name = models.CharField(max_length=256, db_index=True)
    measure = models.CharField(max_length=126,
                               verbose_name='Единица измерения')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Ингредиент'
        verbose_name_plural = "Ингредиенты"

    def __str__(self):
        return f'{self.name}, {self.measure}'


class RecipeQuerySet(models.QuerySet):
    def with_is_favorite(self, user_id):
        """Annotate with favorite flag."""
        return self.annotate(is_favorite=Exists(
            FavoriteRecipes.objects.filter(
                user_id=user_id,
                favor_id=OuterRef('pk'),
            ),
        ))

    def with_is_purchase(self, user_id):
        """Annotate with purchase flag"""
        return self.annotate(is_purchase=Exists(
            Purchase.objects.filter(
                user_id=user_id,
                recipe_id=OuterRef('pk'),
            ),
        ))


class Recipe(models.Model):
    title = models.CharField(max_length=256,
                             verbose_name='Название рецепта')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='recipes',
                               verbose_name='Автор')
    image = models.ImageField(upload_to='posts/',
                              verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание')
    pub_date = models.DateTimeField("date published",
                                    auto_now_add=True)
    cooking_time = models.PositiveSmallIntegerField(
        verbose_name='Время приготовления',
        validators=[MinValueValidator(1)])
    tags = models.ManyToManyField(
        'Tag',
        related_name='recipes',
        verbose_name='Теги'
    )
    ingredients = models.ManyToManyField(Ingredient,
                                         through='RecipeIngredient',
                                         verbose_name='Ингредиенты')

    objects = RecipeQuerySet.as_manager()

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = "Рецепты"
        ordering = ['-pub_date']

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient,
                                   on_delete=models.CASCADE,
                                   verbose_name='Ингредиент',
                                   related_name='amount')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE,
                               related_name='amount')
    amount = models.PositiveSmallIntegerField(
        verbose_name='Количество',
        validators=[MinValueValidator(1)]
    )

    class Meta:
        verbose_name = 'Ингредиент для рецепта'
        verbose_name_plural = "Ингредиенты для рецепта"

    def __str__(self):
        return f'{self.ingredient} в {self.recipe}'


class FollowAuthor(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = "Подписки"
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_followgroup'),
        ]

    def clean(self):
        if self.author == self.user:
            raise ValidationError(
                'Пользователь не может подписываться сам на себя'
            )

    def __str__(self):
        return f'{self.user} подписан на {self.author}'


class FavoriteRecipes(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='favorites', blank=True, null=True)
    favor = models.ForeignKey(Recipe,
                              on_delete=models.CASCADE,
                              related_name='selected', blank=True, null=True)

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = "Избранное"
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'favor'],
                name='unique_favorgroup'),
        ]

    def __str__(self):
        return f'{self.user.username}, {self.favor}'


class Purchase(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='purchase')
    recipe = models.ForeignKey(Recipe,
                               on_delete=models.CASCADE,
                               related_name='purchase')

    class Meta:
        verbose_name = 'Покупка'
        verbose_name_plural = "Покупки"
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'recipe'],
                name='unique_purchasegroup'),
        ]

    def __str__(self):
        return f'{self.user} покупает {self.recipe}'

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} Рецепты {% endblock %}</title>
    {% load static %}
    {% block head %} <link rel="stylesheet" href="{% static 'pages/index.css' %}"> {% endblock %}

</head>
<body class="body">
    {% include 'small_templates/nav.html' %}
<main class="main container">
    {% block header %} {% endblock %}
    {% block content %} {% endblock %}
</main>
{% include 'small_templates/footer.html' %}
</body>

</html>

templates/favorite_index.html
{% extends 'base.html' %}
{% block title %}Избранное{% endblock %}
{% block content %}
{% load static %}
        <div class="main__header">
            <h1 class="main__title">Избранное</h1>
            <ul class="tags">
                {% include './includes/tags_filtration.html' %}
            </ul>

        </div>
        <div class="card-list">
            {% include 'includes/card_item.html' %}
        </div>
        {% if page.has_other_pages %}
            {% include 'includes/paginator.html' with items=page paginator=paginator %}
        {% endif %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/Favorites.js' %}"></script>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'favorite.js' %}"></script>
{% endblock %}

templates/follower_index.html
{% extends 'base.html' %}
{% block title %} Мои подписки{% endblock %}
{% block head %}
{% load static %}
    <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}
{% block content %}
{% load user_filter %}
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
        {% for author in page %}
        <div class="card-user" data-author="{{ author.id }}">
        <div class="card-user__header">
            <h2 class="card-user__title"> {{ author.get_full_name }}</h2>
        </div>
        <div class="card-user__body">
            <ul class="card-user__items">
                {% for recipe in author.recipes.all %}
                {% if forloop.counter < 4 %}
                <li class="card-user__item">
                    <div class="recipe">
                        <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="recipe__image">
                        <h3 class="recipe__title">{{ recipe.title }} </h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time }} мин.</p>
                    </div>
                </li>
                {% endif %}
                {% endfor %}
                {% if author.recipes.all.count > 3 %}
                <li class="card-user__item">
                    <a href="{% url 'profile' author.username %}" class="card-user__link link">Еще {{ author.recipes.all.count|add:"-3"|remaining_recipes }}...</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="card-user__footer">
            <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
        </div>
    </div>
        {% endfor %}

    </div>
    {% if page.has_other_pages %}
            {% include 'paginator.html' with items=page paginator=paginator %}
        {% endif %}

<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

templates/formRecipe.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Создание рецепта</title>
    <link rel="stylesheet" href="./pages/form.css">
</head>
<body class="body">
<header class="header">
    <nav class="nav">
        <div class="nav__container container">
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Рецепты</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Мои подписки</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Создать рецепт</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Избранное</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter"></span></li>

            </ul>
            <ul class="nav__items list">
                <li class="nav__item"><a href="#" class="nav__link link">Изменить пароль</a></li>
                <li class="nav__item"><a href="#" class="nav__link link">Выход</a></li>
            </ul>
        </div>
    </nav>
</header>
<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="name" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        <div class="tags__item">
                            <input type="checkbox" name="breakfast" id="id_breakfast" class="tags__checkbox tags__checkbox_style_orange">
                            <label for="id_breakfast" class="tags__label">Завтрак</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="lunch" id="id_lunch" class="tags__checkbox tags__checkbox_style_green" checked>
                            <label for="id_lunch" class="tags__label">Обед</label>
                        </div>
                        <div class="tags__item">
                            <input type="checkbox" name="dinner" id="id_dinner" class="tags__checkbox tags__checkbox_style_purple" checked>
                            <label for="id_dinner" class="tags__label">Ужин</label>
                        </div>
                    </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">

                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="name" class="form__input">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8" class="form__textarea"></textarea>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <input type="file" name="file" id="id_file">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>


</main>
<footer class="footer">
    <div class="footer__container container">
        <a href="#" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="#" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="#" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>
<script src="./js/config/config.js"></script>
<script src="./js/components/Header.js"></script>
<script src="./js/utils/debouncing.js"></script>
<script src="./js/api/Api.js"></script>
<script src="formRecipe.js"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="main__header">
            <h1 class="main__title">Рецепты</h1>
            {% include './includes/tags_filtration.html' %}
        </div>
        <div class="card-list">
            {% include 'includes/card_item.html' %}
    </div>
        {% if page.has_other_pages %}
            {% include 'includes/paginator.html' with items=page paginator=paginator %}
        {% endif %}
  <script src="{% static 'js/components/MainCards.js' %}"></script>

  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/CardList.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'indexAuth.js' %}"></script>
{% endblock %}

templates/new_recipe.html
{% extends 'base.html' %}
{% block title %} Создание рецепта {% endblock %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
{% block content %}
{% load user_filters %}
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        {% if edit %}
        <form class="form" method="post" enctype="multipart/form-data" action="{% url 'edit' recipe.id %}" >
        {% else %}
            <form class="form" method="post" enctype="multipart/form-data" action="{% url 'new' %}" >
                {% endif %}
            {% csrf_token %}
            {% for field in form %}
            <div class="form__group">
                <label for="{{ field.id_for_label }}" class="form__label">{{ field.label }}</label>
                <div class="form__field-group">
                    {{ field|addclass:"form__input" }}
                </div>
            </div>
            {% endfor %}
            <div class="form__footer">
                <button type="submit" class="button button_style_blue">{% if edit %}Редактировать{% else %}Создать{% endif %} рецепт</button>
            </div>
        </form>
    </div>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{%static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/utils/debouncing.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

templates/one_more_recipe.html
{% extends 'base.html' %}}
{% block title %}Создание рецепта{% endblock %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'pages/form.css' %}">
{% endblock %}
{% block content %}
{% load user_filters %}
<div class="main__header">
  <h1 class="main__title">Создание рецепта</h1>
</div>
<div class="form-container">
  <form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form__group">
      <label for="{{ from.title.id_for_label }}" class="form__label">Название рецепта</label>
      <div class="form__field-group">
        <input
          type="{{ form.title.widget_type }}"
          id="{{ form.title.id_for_label }}"
          name="{{ form.title.html_name }}"
          value="{{ form.title.value|default_if_none:'' }}"
          class="form__input" required>
        <span class="form__error">{{ form.title.errors }}</span>
      </div>
    </div>

    <div class="form__group">
      <p class="form__label">Теги</p>
      <div class="form__field-group">
        <div class="tags">
          {% for tag in form.fields.tags.choices.queryset %}
            <div class="tags__item">
              <input
                type="checkbox"
                name="tags"
                id="id_{{ tag.name }}"
                class="tags__checkbox  tags__checkbox_style_{{ tag.color }}"
                value="{{ tag.pk }}"
                {% if tag.pk in form.tags.value %}checked{% endif %}>
              <label for="id_{{ tag.name }}" class="tags__label">{{ tag.display_name }}</label>
            </div>
          {% endfor %}
        </div>
        <span class="form__error">{{ form.tags.errors }}</span>
      </div>
    </div>

    <div class="form__group">
      <label for="nameIngredient" class="form__label">Ингредиенты</label>
      <div class="form__field-group">
        <div class="form__field-group-ingredientes">
          <div class="form__dropdown">
            <input type="text" id="nameIngredient" class="form__input">
            <div class="form__dropdown-items"></div>
          </div>
          <input type="number" id="cantidad" class="form__input" min="0">
          <label for="cantidad" class="form__label" id="cantidadVal"> шт.</label>
        </div>
        <div class="form__field-group-ingredientes-container">
          {% for ingr in recipe.amount.all %}
            <div class="form__field-item-ingredient" id="ing_{{ forloop.counter }}">
              <span> {{ ingr.ingredient.name }} {{ ingr.amount }} {{ ingr.ingredient.measure }}</span>
              <span class="form__field-item-delete"></span>
              <input id="nameIngredient_{{ forloop.counter }}" name="nameIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingr.ingredient.name }}">
              <input id="valueIngredient_{{ forloop.counter }}" name="valueIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingr.amount }}">
              <input id="unitsIngredient_{{ forloop.counter }}" name="unitsIngredient_{{ forloop.counter }}" type="hidden" value="{{ ingr.ingredient.measure }}">
            </div>
          {% endfor %}
          {% if not valid %}
          <span class="form__error">Выберите хотя бы один ингредиент</span>
          {% endif %}
        </div>
        <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
        <span class="form__error"></span>
      </div>
    </div>

    <div class="form__group">
      <label for="{{ form.cooking_time.id_for_label }}" class="form__label">Время приготовления</label>
      <div class="form__field-group form__field-group_time">
        <input
          type="{{ form.cooking_time.widget_type }}"
          id="{{ form.cooking_time.id_for_label }}"
          name="{{ form.cooking_time.html_name }}"
          value="{{ form.cooking_time.value|default_if_none:'' }}"
          class="form__input">
        <label for="{{ form.cooking_time.id_for_label }}" class="form__label">минут</label>
        <span class="form__error">{{ form.cooking_time.errors }}</span>
      </div>
    </div>

    <div class="form__group">
      <label for="{{ form.description.id_for_label }}" class="form__label">Описание</label>
      <div class="form__field-group">
        {{ form.description|addclass:'form__textarea' }}
        <span class="form__error">{{ form.text.errors }}</span>
      </div>
    </div>

    <div class="form__group">
      <span class="form__label">Загрузить фото</span>
      <div class="form__field-group">
        {{ form.image|addclass:'form__file-button' }}
        <span class="form__error">{{ form.image.errors }}</span>
      </div>
    </div>

    <div class="form__footer">
      <button class="button button_style_blue">
        {% if recipe %}
          Сохранить </button> <a style="margin-left: 2.5em" href="{% url 'recipe_delete' recipe.id %}" class="form__ingredient-link">Удалить</a>
        {% else %}
        Создать рецепт
        {% endif %}</button>
    </div>

  </form>
</div>


  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>
  <script src="{% static 'js/utils/debouncing.js' %}"></script>
  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'formRecipe.js' %}"></script>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load user_filter %}
<div class="main__header">
            <h1 class="main__title">{{ author.get_full_name }}</h1>
            <ul class="tags">
                {% include './includes/tags_filtration.html' %}
            </ul>
        </div>
        {% if user.is_authenticated and author != user %}
    <div class="author-subscribe" data-author="{{ author.id }}">
      <p style="padding: 0 0 2em 0;">
        {% if user|is_follow:author %}
          <button class="button button_style_light-blue button_size_subscribe" name="subscribe">
            Отписаться от автора
          </button>
        {% else %}
          <button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>
            Подписаться на автора
          </button>
        {% endif %}
      </p>
    </div>
  {% endif %}
        <div class="card-list">
            {% include 'includes/card_item.html' with page=page %}
    </div>

        {% if page.has_other_pages %}
            {% include 'includes/paginator.html' with items=page paginator=paginator %}
        {% endif %}
<script src="{% static 'js/components/MainCards.js' %}"></script>

  <script src="{% static 'js/components/Purchases.js' %}"></script>
  <script src="{% static 'js/components/Favorites.js' %}"></script>
  <script src="{% static 'js/components/Subscribe.js' %}"></script>

  <script src="{% static 'js/config/config.js' %}"></script>
  <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
  <script src="{% static 'js/components/Header.js' %}"></script>

  <script src="{% static 'js/api/Api.js' %}"></script>
  <script src="{% static 'authorRecipe.js' %}"></script>
{% endblock %}

templates/purchase_index.html
{% extends 'base.html' %}
{% block title %}Список покупок{% endblock %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'pages/shopList.css' %}">
{% endblock %}
{% block content %}
    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for recipe in recipes %}
            <li class="shopping-list__item" data-id="{{ recipe.id }}">
                <div class="recipe recipe_reverse">
                    <img src="{{ recipe.image.url }}" alt="{{ recipe.title }}" class="recipe__image recipe__image_big">
                    <h3 class="recipe__title">{{ recipe.title }}</h3>
                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.cooking_time}} мин.</p>
                </div>
                <button class="shopping-list__button link">Удалить</button>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'get' %}"><button class="button button_style_blue">Скачать список</button></a>


    </div>

<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/ShopList.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'shopList.js' %}"></script>
{% endblock %}